import type {Metadata} from "next";
import {Inter, Merriweather} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/navigation";

const inter = Inter({
    variable: '--font-inter',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

const merriweather = Merriweather({
    variable: '--font-merriweather',
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "NextJS - basic",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${merriweather.variable} antialiased flex min-h-screen flex-col`}>
                <main className={'flex-grow w-full pt-16 font-merriweather'}>
                    <Navigation />
                    {children}
                </main>
            </body>
        </html>
    );
}
